/*테이블 삭제*/
drop table 소비자_주문_테이블;
drop table 화합물;
drop table 협력업체;
drop table 한달총량;
drop table 하루총량;

/*혹시 모를 겹침을 방지하기 위해서 Battery Recycle 의 BR을 붙였습니다.*/
drop table BRORDER;
drop table BRCOMPOUND;
drop table BRFIRM;
drop table BRMONTH;
drop table BRDAY;

/*테이블 생성*/
create table BRORDER(
주문번호 number(20) primary key,
날짜 date,
업체종류 varchar(20),
화합물이름 varchar(20),
무게 number(20),
납부여부 varchar(20));

CREATE TABLE BRCOMPOUND(
    화합물_ID NUMBER(2) PRIMARY KEY,
    화합물이름 VARCHAR2(50),
    무게 NUMBER(10)
);

create table BRFIRM(
ID NUMBER(20) PRIMARY KEY,
업체명 VARCHAR(20),
폐배터리개수 NUMBER(20)
);

CREATE TABLE BRMONTH(
    날짜 NUMBER(2) PRIMARY KEY,
    총량 NUMBER(30)
);

CREATE TABLE BRDAY(
화합물_ID NUMBER(20) PRIMARY KEY,
화합물이름 VARCHAR2(50),
무게 NUMBER(10));

/*테이블 임의의 값 넣기*/

/*화합물*/
INSERT INTO BRCOMPOUND
VALUES(1, 'NickelSulfate', 80);
INSERT INTO BRCOMPOUND
VALUES(2, 'CobaltSulfate', 60);
INSERT INTO BRCOMPOUND
VALUES(3, 'AluminumSulfate', 60);
INSERT INTO BRCOMPOUND
VALUES(4, 'LitiumCarbonate', 110);
INSERT INTO BRCOMPOUND
VALUES(5, 'ManganeseSulfate', 90);
INSERT INTO BRCOMPOUND
VALUES(6, 'NickelSulfate', 80);
INSERT INTO BRCOMPOUND
VALUES(7, 'CobaltSulfate', 70);
INSERT INTO BRCOMPOUND
VALUES(8, 'NiMetal', 120);
INSERT INTO BRCOMPOUND
VALUES(9, 'CoMetal', 130);

/*하루총량*/
INSERT INTO BRDAY
VALUES(1, 'NickelSulfate', 80);
INSERT INTO BRDAY
VALUES(2, 'CobaltSulfate', 60);
INSERT INTO BRDAY
VALUES(3, 'AluminumSulfate', 60);
INSERT INTO BRDAY
VALUES(4, 'LitiumCarbonate', 110);
INSERT INTO BRDAY
VALUES(5, 'ManganeseSulfate', 90);
INSERT INTO BRDAY
VALUES(6, 'NickelSulfate', 80);
INSERT INTO BRDAY
VALUES(7, 'CobaltSulfate', 70);
INSERT INTO BRDAY
VALUES(8, 'NiMetal', 120);
INSERT INTO BRDAY
VALUES(9, 'CoMetal', 130);

/*한달총량*/
INSERT INTO BRMONTH
VALUES(1, 980);
INSERT INTO BRMONTH
VALUES(2, 1080);
INSERT INTO BRMONTH
VALUES(3, 990);
INSERT INTO BRMONTH
VALUES(4, 800);
INSERT INTO BRMONTH
VALUES(5, 1100);
INSERT INTO BRMONTH
VALUES(6, 1010);
INSERT INTO BRMONTH
VALUES(7, 1030);
INSERT INTO BRMONTH
VALUES(8, null);
INSERT INTO BRMONTH
VALUES(9, null);
INSERT INTO BRMONTH
VALUES(10, null);
INSERT INTO BRMONTH
VALUES(11, null);
INSERT INTO BRMONTH
VALUES(12, null);
INSERT INTO BRMONTH
VALUES(13, null);
INSERT INTO BRMONTH
VALUES(14, null);
INSERT INTO BRMONTH
VALUES(15, null);
INSERT INTO BRMONTH
VALUES(16, null);
INSERT INTO BRMONTH
VALUES(17, null);
INSERT INTO BRMONTH
VALUES(18, null);
INSERT INTO BRMONTH
VALUES(19, null);
INSERT INTO BRMONTH
VALUES(20, null);
INSERT INTO BRMONTH
VALUES(21, null);
INSERT INTO BRMONTH
VALUES(22, null);
INSERT INTO BRMONTH
VALUES(23, null);
INSERT INTO BRMONTH
VALUES(24, null);
INSERT INTO BRMONTH
VALUES(25, null);
INSERT INTO BRMONTH
VALUES(26, null);
INSERT INTO BRMONTH
VALUES(27, null);
INSERT INTO BRMONTH
VALUES(28, null);
INSERT INTO BRMONTH
VALUES(29, null);
INSERT INTO BRMONTH
VALUES(30, null);
INSERT INTO BRMONTH
VALUES(31, null);

/*협력업체*/
INSERT INTO BRFIRM
VALUES(1,'민규전자',20);
INSERT INTO BRFIRM
VALUES(2,'성일하이텍',10);
INSERT INTO BRFIRM
VALUES(3,'세빗켐',20);
INSERT INTO BRFIRM
VALUES(4,'고려아연',30);
INSERT INTO BRFIRM
VALUES(5,'ANU', 0);

commit;